server:
  port: 11111

spring:
  application:
    name: legendary-admin
  boot:
    admin:
      ui:
        title: Legendary Admin
      client:
        url:
          - http://localhost:11111
#      instance-auth:
#        default-user-name: admin
#        default-password: admin

management:
  endpoint:
    health:
      show-details: always

# 配置Logfile Viewer 日志挂载
logging:
  file:
    name: logs/${spring.application.name}/all.log
  level:
    root: info