server:
  port: 11111

spring:
  application:
    name: legendary-admin
  boot:
    admin:
      ui:
        title: Legendary Admin
      instance-auth:
        default-user-name: admin
        default-password: admin

management:
  endpoint:
    health:
      show-details: always