server:
  port: 11111

spring:
  boot:
    admin:
      ui:
        title: Legendary Admin
#      instance-auth:
#        default-user-name: admin
#        default-password: admin

management:
  endpoint:
    health:
      show-details: always

# 配置Logfile Viewer 日志挂载
logging:
  level:
    root: info