server:
  port:
    13171

spring:
  security:
    oauth2:
      authorization:
        check-token-access: http://localhost:13181/oauth/check_token
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            #注意这个设置只对 spring boot 2.4+ 有效，低版本 使用  allowedOrigins: "*" 属性
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
      httpclient:
        connect-timeout: 1000
        response-timeout: 10s
      routes:
        # OAuth2
        - id: oauth
          uri: lb://auth-server
          predicates:
            - Path=/oauth/**
        # 用户中心
        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/user_center/**
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          # 使用小写服务名，默认是大写
          lower-case-service-id: true

## 允许匿名访问的白名单
ignore:
  urls:
    - "/swagger-ui.html"
    - "/swagger-resources/**"
    - "/swagger/**"
    - "/webjars/springfox-swagger-ui/**"
    - "/**/v2/api-docs"
    - "/**/*.js"
    - "/**/*.css"
    - "/**/*.png"
    - "/**/*.ico"
    - "/actuator/**"
    - "/oauth/**"