server:
  port:
    13171

spring:
  cloud:
    gateway:
      routes:
        # OAuth2
        - id: oauth
          uri: lb://auth-server
          predicates:
            - Path=/oauth/token
        # 用户中心
        - id: user-center
          uri: lb://user-center
          predicates:
            - Path=/sys_user/**
            - Path=/sys_user_role_relation/**
            - Path=/sys_role/**
            - Path=/sys_role_permission_relation/**
            - Path=/sys_permission/**
            - Path=/sys_user_info/**
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能
          enabled: true
          # 使用小写服务名，默认是大写
          lower-case-service-id: true