# 配置启动端口
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8081

spring:
  application:
    name: Api
  # 环境 dev|test|prod
  profiles:
    active: dev


# MybatisPlus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-field: flag
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath*:/mapper/*.xml,classpath*:/mapper/**/*.xml
  type-aliases-package: classpath:com.yy.mbg.domain.entity


