server:
  port: 13191
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:32306/legendary?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true

dubbo:
  scan:
    base-packages:
      - pers.legendary.business.user.service.impl
  registry:
    address: nacos://127.0.0.1:31848
    timeout: 50000
  protocol:
    name: dubbo
    port: -1

logging:
  file:
    name: logs/${spring.application.name}/all.log
  level:
    root: info
    pers.legendary.common.mbg.rbac.mapper: debug