server:
  port: 13181

spring:
  redis:
    database: 0
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/legendary?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
dubbo:
  scan:
    base-packages:
      - pers.legendary.auth.server
  registry:
    address: nacos://127.0.0.1:8848
    timeout: 50000
  protocol:
    name: dubbo
    port: -1

logging:
  file:
    name: logs/${spring.application.name}/all.log
  level:
    root: info
