server:
  port: 13191
  servlet:
    context-path: /user_center
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/legendary?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  security:
    oauth2:
      client:
        client-id: gateway-client
        client-secret: gateway-client
      authorization:
        check-token-access: http://localhost:13181/oauth/check_token

dubbo:
  scan:
    base-packages:
      - pers.legendary.business.user.service.impl
  registry:
    address: nacos://127.0.0.1:8848
    timeout: 50000
  protocol:
    name: dubbo
    port: -1
