# 依赖的基础镜像jdk8
FROM openjdk:8-jdk-alpine
# 作者信息
MAINTAINER YangYang
# 将本地文件挂载到当前容器
VOLUME /tmp
# 定义进入容器时默认位置，接下来后续操作的工作位置
WORKDIR /home/legendary
# 需要暴露出去的端口，但不会主动暴露
EXPOSE 13191
# 复制配置文件便于修改
COPY /target/classes/bootstrap.yml ./config/bootstrap.yml
# 将上下文中.jar复制到工作目录
ADD /target/user-center-0.0.1.jar user-center.jar
# 启动容器之后，默认的运行命令
# 开启远程调试：-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005
ENTRYPOINT ["java","-jar","-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005","user-center.jar"]