# 配置启动端口
server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080

spring:
  application:
    name: Core
  # 环境 dev|test|prod
  profiles:
    active: dev

  redis:
    open: true  # 是否开启redis缓存  true开启   false关闭
    database: 0
    host: localhost
    port: 6379
    password:    # 密码（默认为空）
    timeout: 6000ms  # 连接超时时长（毫秒）
    keyPrefix: ""
#    lettuce:
#      pool:
#        max-active: 1000 # 连接池最大连接数（使用负值表示没有限制）
#        max-idle: 10 # 连接池中的最大空闲连接
#        max-wait: -1ms  # 连接池最大阻塞等待时间（使用负值表示没有限制）
#        min-idle: 5 # 连接池中的最小空闲连接